// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkQ9YEw_lTPU4qtw-sRp2s1Y4N81eoEls',
    appId: '1:218381152326:web:5a774a17ee143e605f5a47',
    messagingSenderId: '218381152326',
    projectId: 'newproject01-f853c',
    authDomain: 'newproject01-f853c.firebaseapp.com',
    storageBucket: 'newproject01-f853c.appspot.com',
    measurementId: 'G-65H3XC5ZE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_fQDPiMAUyX-0ovLv7zbHOZPGD-IYqAQ',
    appId: '1:218381152326:android:01f18e5f500e79485f5a47',
    messagingSenderId: '218381152326',
    projectId: 'newproject01-f853c',
    storageBucket: 'newproject01-f853c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmBn0l91sJjNnFVPNu0Q-Yyb5RaN7_tsI',
    appId: '1:218381152326:ios:40ce263067b9bf085f5a47',
    messagingSenderId: '218381152326',
    projectId: 'newproject01-f853c',
    storageBucket: 'newproject01-f853c.appspot.com',
    iosBundleId: 'com.example.newproject01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmBn0l91sJjNnFVPNu0Q-Yyb5RaN7_tsI',
    appId: '1:218381152326:ios:4bedb96d1b9849765f5a47',
    messagingSenderId: '218381152326',
    projectId: 'newproject01-f853c',
    storageBucket: 'newproject01-f853c.appspot.com',
    iosBundleId: 'com.example.newproject01.RunnerTests',
  );
}
